version: '3.8'

services:
   php:
    build: ./
    ports:
      - "8000:00"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.3
    container_name: postgis
    ports:
      - "5434:5434"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escape_game
    volumes:
      - ./MY_escape_game.sql:/docker-entrypoint-initdb.d/MY_escape_game.sql

  geoserver:
    image: kartoza/geoserver
    ports:
      - "8080:8080"
    volumes:
      - ./:/opt/geoserver/data_dir

networks:
  default:
    driver: bridge