version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escape_game
    ports:
      - "5434:5434"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escape_game
    ports:
      - "5434:5434"
    volumes:
      - pgdata:/var/lib/postgresql/data

  geoserver:
    image: oscarfonts/geoserver:latest
    environment:
      - GEOSERVER_ADMIN_PASSWORD=admin
      - GEOSERVER_ADMIN_USER=geoserver
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./data:/opt/geoserver/data_dir  # Persister les données de GeoServer

volumes:
  pgdata: