version: '3.8'

services:
  postgis:
    build:
      context: .
      dockerfile: POSTGIS
    container_name: postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: france_data
    ports:
      - "5434:5434"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  geoserver:
    build:
      context: .
      dockerfile: GEOSERVER
    container_name: geoserver
    depends_on:
      - postgis
    ports:
      - "8080:8080"
    volumes:
      - geoserver_data:/var/geoserver_data

  php:
    build:
      context: .
      dockerfile: PHP
    container_name: php_app
    depends_on:
      - postgis
    ports:
      - "8000:8000"
    volumes:
      - ./php:/var/www/html

volumes:
  postgis_data:
  geoserver_data: